version: '3.2'
services:

  rabbitmq:
    image: rabbitmq:3.7-management
    environment:
      RABBITMQ_DEFAULT_USER: ${QUEUE_USER}
      RABBITMQ_DEFAULT_PASS: ${QUEUE_PASSWORD}

  clickhouse:
    image: yandex/clickhouse-server
    volumes:
      - ./docker/clickhouse/config.xml:/etc/clickhouse-server/config.xml
      - ./docker/clickhouse/users.xml:/etc/clickhouse-server/users.xml

  postgresql:
    image: postgres:latest
    volumes:
      - ./migrations/postgresql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

  js_build:
    build:
      context: ./docker/js_build
    volumes:
      - ./:/data
    command: npm ci

  app:
    build:
      context: ./docker/app
    depends_on:
      - postgresql
      - clickhouse
      - rabbitmq
      - js_build
    volumes:
      - ./:/var/www/app

  nginx:
    image: nginx:latest
    depends_on:
      - app
    ports:
      - 3333:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www
