version: '3.2'
services:

  rabbitmq:
    image: rabbitmq:3.7-management
    environment:
    - RABBITMQ_DEFAULT_USER=${RABBITMQ_LOGIN}
    - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}

  clickhouse:
    image: yandex/clickhouse-server

  postgresql:
    image: postgres:latest

  nginx:
    image: nginx:latest

  app:
    image: node:10-alpine
    volumes:
      - .:/var/www/app

volumes:
  dbdata:
