CREATE TABLE IF NOT EXISTS targets (
  token UUID PRIMARY KEY,
  name VARCHAR(40) NOT NULL,
  active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
